/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Therapist } from "./Therapist";
import { TherapistCountArgs } from "./TherapistCountArgs";
import { TherapistFindManyArgs } from "./TherapistFindManyArgs";
import { TherapistFindUniqueArgs } from "./TherapistFindUniqueArgs";
import { DeleteTherapistArgs } from "./DeleteTherapistArgs";
import { TherapistService } from "../therapist.service";
@graphql.Resolver(() => Therapist)
export class TherapistResolverBase {
  constructor(protected readonly service: TherapistService) {}

  async _therapistsMeta(
    @graphql.Args() args: TherapistCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Therapist])
  async therapists(
    @graphql.Args() args: TherapistFindManyArgs
  ): Promise<Therapist[]> {
    return this.service.therapists(args);
  }

  @graphql.Query(() => Therapist, { nullable: true })
  async therapist(
    @graphql.Args() args: TherapistFindUniqueArgs
  ): Promise<Therapist | null> {
    const result = await this.service.therapist(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Therapist)
  async deleteTherapist(
    @graphql.Args() args: DeleteTherapistArgs
  ): Promise<Therapist | null> {
    try {
      return await this.service.deleteTherapist(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
