/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Spa } from "./Spa";
import { SpaCountArgs } from "./SpaCountArgs";
import { SpaFindManyArgs } from "./SpaFindManyArgs";
import { SpaFindUniqueArgs } from "./SpaFindUniqueArgs";
import { DeleteSpaArgs } from "./DeleteSpaArgs";
import { SpaService } from "../spa.service";
@graphql.Resolver(() => Spa)
export class SpaResolverBase {
  constructor(protected readonly service: SpaService) {}

  async _spasMeta(
    @graphql.Args() args: SpaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Spa])
  async spas(@graphql.Args() args: SpaFindManyArgs): Promise<Spa[]> {
    return this.service.spas(args);
  }

  @graphql.Query(() => Spa, { nullable: true })
  async spa(@graphql.Args() args: SpaFindUniqueArgs): Promise<Spa | null> {
    const result = await this.service.spa(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Spa)
  async deleteSpa(@graphql.Args() args: DeleteSpaArgs): Promise<Spa | null> {
    try {
      return await this.service.deleteSpa(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
